name: Lighthouse Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Install dependencies
        run: npm install

      - name: Build and start the project
        run: npm run build && npm start &

      - name: Wait for the application to start
        run: sleep 10

      - name: Run Lighthouse CI
        run: npm run lighthouse-ci
